sculpin_content_types:
    posts:
        permalink: blog/:year/:month/:day/:filename/
    meetings:
        permalink: meeting/:year/:filename/
        type: path
        path: _meetings
        singular_name: meeting
        layout: meeting
        enabled: true
        taxonomies:
          - tags